### ISSUE TITLE
Neovim v0.10.0 Upgrade Color Changes

### ISSUE THREAD

**Issue by kaykhan** [sainnhe/sonokai#100] opened 2024-06-02 14:41 UTC
HI friends, i recently had time to upgrade to neovim v0.10.0 and i noticed the text color has changed (despite no change in my theme)

v0.9.1
![image](https://github.com/sainnhe/sonokai/assets/5202527/16d50d45-ceae-4d94-9e60-5fcd48f297d9)

v0.10.0
![image](https://github.com/sainnhe/sonokai/assets/5202527/39b5183c-cc12-4b6e-ba74-20c5155ad938)

- You can see in the orignal there is alot more orange with the variables (users, UsersError)
- You can also see the function names changed from Green to Blue (AuthUser)

Is there a highlight group which corresponds to both of these?

**Comment by antoineco** [comment] 2024-06-02 14:56
Could you please move your cursor to the word that looks different in Neovim 0.10 and post the output of the `:Inspect` command?

**Comment by kaykhan** [comment] 2024-06-02 16:28
Oh i did not know about this Inspect feature

v0.10.0
![image](https://github.com/sainnhe/sonokai/assets/5202527/7791d92e-0dd0-4e54-bdde-d8dd27e02d00)

**Comment by antoineco** [comment] 2024-06-02 18:04
The 0.10 highlight is the correct one:

https://github.com/sainnhe/sonokai/blob/a1be1ff2a9eeacfad064277603c3913a8a9be212/colors/sonokai.vim#L520

I am not sure why it was linking to `Identifier` in 0.9. You might be able to find the answer with the following commands:

```vim
:verbose highlight @lsp.type.variable
:verbose highlight @lsp.type.variable.typescript
```

Are you sure that you are using the same revision of Sonokai in both Neovim releases?

**Comment by antoineco** [comment] 2024-06-04 08:11
I wasn't able to reproduce on Neovim v0.9.1 with a fresh configuration including only the following plugins:
- `sainnhe/sonokai`
- `nvim-treesitter/nvim-treesitter` (`typescript` grammar installed)
- `neovim/nvim-lspconfig` (`tsserver` enabled)

![image](https://github.com/sainnhe/sonokai/assets/3299086/0f85b6fb-beff-4339-a226-f93d269e790f)

Here are some details about my setup.

```console
$ :version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

```lua
-- init.lua
require "lspconfig".tsserver.setup {}  -- LSP server config
```

```console
$ :!typescript-language-server --version
4.3.3
```

```console
$ :LspInfo
Client: tsserver (id: 1, bufnr: [1])
```

```console
$ :Inspect  # on 'user' at line 16
Treesitter
  - @variable.typescript links to Fg typescript

Semantic Tokens
  - @lsp.type.variable.typescript links to Fg priority: 125
  - @lsp.mod.declaration.typescript links to @lsp priority: 126
  - @lsp.mod.readonly.typescript links to @lsp priority: 126
  - @lsp.typemod.variable.declaration.typescript links to @lsp priority: 127
  - @lsp.typemod.variable.readonly.typescript links to @lsp priority: 127
```

```console
$ :verbose highlight @lsp.type.variable.typescript
(nothing)
```

```console
$ :verbose highlight @lsp.type.variable
@lsp.type.variable xxx links to TSVariable
        Last set from ~/.local/share/nvim/lazy/sonokai/colors/sonokai.vim line 670
```

![image](https://github.com/sainnhe/sonokai/assets/3299086/205b2f3b-bd8c-45e3-93bc-055a63d919e4)

I conclude that `@lsp.type.variable.typescript` is being linked to `Identifier` by either another plugin, or some user configuration.

Since the issue is not related to sonokai I am now closing the issue, however feel free to keep discussing in case you need help troubleshooting.

**Closed by antoineco** 2024-06-04 08:11 UTC
Labels: question, can't reproduce
